# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('commitment_value', models.CharField(max_length=256)),
            ],
        ),
    ]
