# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0003_commitment_created_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
