# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0004_auto_20170227_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentReadability',
            fields=[
                ('commitment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='commitments.Commitment')),
            ],
        ),
    ]
