# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0005_commitmentreadability'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentreadability',
            name='readable',
            field=models.BooleanField(default=False),
        ),
    ]
