# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0007_auto_20170227_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitmentreadability',
            name='readable',
        ),
        migrations.AddField(
            model_name='commitmentreadability',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commitmentreadability',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commitments.Commitment', unique=True),
        ),
    ]
