# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0009_auto_20170227_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitmentreadability',
            name='id',
        ),
        migrations.AlterField(
            model_name='commitmentreadability',
            name='commitment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='commitments.Commitment'),
        ),
    ]
