# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0010_auto_20170227_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentreadability',
            name='readable',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
