# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0011_commitmentreadability_readable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentreadability',
            name='readable',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
