# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0013_auto_20170227_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentreadability',
            name='commitment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='readability', serialize=False, to='commitments.Commitment'),
        ),
    ]
